nozama:
    build: .
    ports:
     - "5000:5000"
    links:
     - "mongo"
     - "elasticsearch"
mongo:
    image: mongo:latest
genghis:
    image: aegypius/genghis
    command: /usr/local/bundle/bin/genghisapp  --no-launch --foreground --port=5000 --servers mongo_1:27017
    ports:
     - "5001:5000"
    links:
     - "mongo"
elasticsearch:
    image: elasticsearch